export const LOGOS = {
    'Miami Heat': 'https://loodibee.com/wp-content/uploads/miami-heat-logo-symbol.png',
    'Boston Celtics': 'https://content.sportslogos.net/logos/6/213/full/boston_celtics_logo_primary_19977628.png',
    'Brooklyn Nets': 'https://loodibee.com/wp-content/uploads/nba-brooklyn-nets-logo.png',
    'Chicago Bulls': 'https://loodibee.com/wp-content/uploads/nba-chicago-bulls-logo.png',
    'Phoenix Suns': 'https://loodibee.com/wp-content/uploads/phoenix-suns-logo-symbol.png',
    'Denver Nuggets': 'https://loodibee.com/wp-content/uploads/denver-nuggets-logo-symbol.png',
    'Golden State Warriors': 'https://loodibee.com/wp-content/uploads/nba-golden-state-warriors-logo-2020.png',
    'Indiana Pacers': 'https://loodibee.com/wp-content/uploads/indiana-pacers-logo-symbol.png',
    'Milwaukee Bucks': 'https://loodibee.com/wp-content/uploads/milwaukee-bucks-logo-symbol.png',
    'New Orleans Pelicans': 'https://loodibee.com/wp-content/uploads/new-orleans-pelicans-logo-symbol.png',
    'Oklahoma City Thunder': 'https://loodibee.com/wp-content/uploads/oklahoma-city-thunder-logo-symbol.png',
    'Philadelphia 76ers': 'https://loodibee.com/wp-content/uploads/nba-philadelphia-76ers-logo.png',
    'Sacramento Kings': 'https://loodibee.com/wp-content/uploads/nba-sacramento-kings-logo.png',
    'Toronto Raptors': 'https://loodibee.com/wp-content/uploads/nba-toronto-raptors-logo.png',
    'Cleveland Cavaliers': 'https://content.sportslogos.net/logos/6/222/full/cleveland_cavaliers_logo_alternate_2023_sportslogosnet-5447.png',
    'Los Angeles Lakers': 'https://www.freepnglogos.com/uploads/lakers-logo-png/los-angeles-png-lakers-symbol-icon-7.png',
    'LA Clippers': 'https://loodibee.com/wp-content/uploads/los-angeles-clippers-logo-symbol.png',
    'Charlotte Hornets': 'https://loodibee.com/wp-content/uploads/nba-charlotte-hornets-logo.png',
    'Atlanta Hawks': 'https://loodibee.com/wp-content/uploads/nba-atlanta-hawks-logo.png',
    'Dallas Mavericks': 'https://loodibee.com/wp-content/uploads/dallas-mavericks-logo-symbol.png',
    'Detroit Pistons': 'https://loodibee.com/wp-content/uploads/nba-detroit-pistons-logo.png',
    'Houston Rockets': 'https://loodibee.com/wp-content/uploads/houston-rockets-logo-symbol.png',
    'Memphis Grizzlies': 'https://loodibee.com/wp-content/uploads/nba-memphis-grizzlies-logo.png',
    'Minnesota Timberwolves': 'https://loodibee.com/wp-content/uploads/nba-minnesota-timberwolves-logo.png',
    'New York Knicks': 'https://content.sportslogos.net/logos/6/216/full/new_york_knicks_logo_primary_2023_sportslogosnet-8036.png',
    'Orlando Magic': 'https://loodibee.com/wp-content/uploads/orlando-magic-logo-symbol.png',
    'Portland Trail Blazers': 'https://loodibee.com/wp-content/uploads/portland-trail-blazers-logo-symbol.png',
    'San Antonio Spurs': 'https://loodibee.com/wp-content/uploads/san-antonio-spurs-logo-symbol.png',
    'Utah Jazz': 'https://content.sportslogos.net/logos/6/234/full/utah_jazz_logo_alternate_2023_sportslogosnet-5515.png',
    'Washington Wizards': 'https://loodibee.com/wp-content/uploads/washington-wizards-logo-symbol.png'
}